/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as UntitledLettersRouteImport } from './routes/untitled-letters'
import { Route as WarningLettersRouteImport } from './routes/warning-letters'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LettersIdRouteImport } from './routes/letters.$id'
import { Route as ApiLetterFileIdRouteImport } from './routes/api/letter-file.$id'
import { Route as ApiLetterPdfIdRouteImport } from './routes/api/letter-pdf.$id'
import { Route as ApiPublicHooksIngestLettersRouteImport } from './routes/api/public/hooks/ingest-letters'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UntitledLettersRoute = UntitledLettersRouteImport.update({
  id: '/untitled-letters',
  path: '/untitled-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const WarningLettersRoute = WarningLettersRouteImport.update({
  id: '/warning-letters',
  path: '/warning-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIdRoute = LettersIdRouteImport.update({
  id: '/letters/$id',
  path: '/letters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLetterFileIdRoute = ApiLetterFileIdRouteImport.update({
  id: '/api/letter-file/$id',
  path: '/api/letter-file/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLetterPdfIdRoute = ApiLetterPdfIdRouteImport.update({
  id: '/api/letter-pdf/$id',
  path: '/api/letter-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestLettersRoute =
  ApiPublicHooksIngestLettersRouteImport.update({
    id: '/api/public/hooks/ingest-letters',
    path: '/api/public/hooks/ingest-letters',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/untitled-letters': typeof UntitledLettersRoute
  '/warning-letters': typeof WarningLettersRoute
  '/api/chat': typeof ApiChatRoute
  '/letters/$id': typeof LettersIdRoute
  '/api/letter-file/$id': typeof ApiLetterFileIdRoute
  '/api/letter-pdf/$id': typeof ApiLetterPdfIdRoute
  '/api/public/hooks/ingest-letters': typeof ApiPublicHooksIngestLettersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/untitled-letters': typeof UntitledLettersRoute
  '/warning-letters': typeof WarningLettersRoute
  '/api/chat': typeof ApiChatRoute
  '/letters/$id': typeof LettersIdRoute
  '/api/letter-file/$id': typeof ApiLetterFileIdRoute
  '/api/letter-pdf/$id': typeof ApiLetterPdfIdRoute
  '/api/public/hooks/ingest-letters': typeof ApiPublicHooksIngestLettersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/untitled-letters': typeof UntitledLettersRoute
  '/warning-letters': typeof WarningLettersRoute
  '/api/chat': typeof ApiChatRoute
  '/letters/$id': typeof LettersIdRoute
  '/api/letter-file/$id': typeof ApiLetterFileIdRoute
  '/api/letter-pdf/$id': typeof ApiLetterPdfIdRoute
  '/api/public/hooks/ingest-letters': typeof ApiPublicHooksIngestLettersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/untitled-letters'
    | '/warning-letters'
    | '/api/chat'
    | '/letters/$id'
    | '/api/letter-file/$id'
    | '/api/letter-pdf/$id'
    | '/api/public/hooks/ingest-letters'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/untitled-letters'
    | '/warning-letters'
    | '/api/chat'
    | '/letters/$id'
    | '/api/letter-file/$id'
    | '/api/letter-pdf/$id'
    | '/api/public/hooks/ingest-letters'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/auth'
    | '/untitled-letters'
    | '/warning-letters'
    | '/api/chat'
    | '/letters/$id'
    | '/api/letter-file/$id'
    | '/api/letter-pdf/$id'
    | '/api/public/hooks/ingest-letters'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  UntitledLettersRoute: typeof UntitledLettersRoute
  WarningLettersRoute: typeof WarningLettersRoute
  ApiChatRoute: typeof ApiChatRoute
  LettersIdRoute: typeof LettersIdRoute
  ApiLetterFileIdRoute: typeof ApiLetterFileIdRoute
  ApiLetterPdfIdRoute: typeof ApiLetterPdfIdRoute
  ApiPublicHooksIngestLettersRoute: typeof ApiPublicHooksIngestLettersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/untitled-letters': {
      id: '/untitled-letters'
      path: '/untitled-letters'
      fullPath: '/untitled-letters'
      preLoaderRoute: typeof UntitledLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warning-letters': {
      id: '/warning-letters'
      path: '/warning-letters'
      fullPath: '/warning-letters'
      preLoaderRoute: typeof WarningLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/$id': {
      id: '/letters/$id'
      path: '/letters/$id'
      fullPath: '/letters/$id'
      preLoaderRoute: typeof LettersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/letter-file/$id': {
      id: '/api/letter-file/$id'
      path: '/api/letter-file/$id'
      fullPath: '/api/letter-file/$id'
      preLoaderRoute: typeof ApiLetterFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/letter-pdf/$id': {
      id: '/api/letter-pdf/$id'
      path: '/api/letter-pdf/$id'
      fullPath: '/api/letter-pdf/$id'
      preLoaderRoute: typeof ApiLetterPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-letters': {
      id: '/api/public/hooks/ingest-letters'
      path: '/api/public/hooks/ingest-letters'
      fullPath: '/api/public/hooks/ingest-letters'
      preLoaderRoute: typeof ApiPublicHooksIngestLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  UntitledLettersRoute: UntitledLettersRoute,
  WarningLettersRoute: WarningLettersRoute,
  ApiChatRoute: ApiChatRoute,
  LettersIdRoute: LettersIdRoute,
  ApiLetterFileIdRoute: ApiLetterFileIdRoute,
  ApiLetterPdfIdRoute: ApiLetterPdfIdRoute,
  ApiPublicHooksIngestLettersRoute: ApiPublicHooksIngestLettersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
